### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by Higgsi** [sk-k1ng/spectrum#1]
used this with my actual tiktok credentials and still didn't find the password

**Comment by sk-k1ng** [comment]
Hello, I have solved this error. It was a simple error in the if. Update the repository in the terminal and it will work.

**Comment by Higgsi** [comment]
Yeah i noticed that error but thats not my issue. I tried the script on my tiktok account using a wordlist wi 5 passwords, one of which is the right one. Goes through the worslist but doesnt actually do anything else

**Comment by Higgsi** [comment]
Tiktok have changed there front end so dont think it's possible to brute force now unless u use a proxy

**Comment by sk-k1ng** [comment]
I will check if that is true and try to add proxy
